#!/bin/sh

TABLE=../h/xevact_tests_table.h
DECLARE=../h/xevact_tests_declare.h

#erase old table
echo >$TABLE
echo >$DECLARE
echo >Makefile

echo -n 'OBJS=' >>Makefile

TESTS=*.c
for x in $TESTS; do
	FUNCNAME=`basename $x .c`
	echo "{\"$FUNCNAME\", CALL_TEST, $FUNCNAME}," >>$TABLE
	echo -n "$FUNCNAME.o " >>Makefile
	echo "Bool $FUNCNAME" '(Action *action, XEvent *xev, int tnum) ;' >>$DECLARE
	done

echo >>Makefile
echo >>Makefile
echo '.c.o:' >>Makefile
echo '	$(CC) $(CFLAGS) -c $*.c -o $*.o' >>Makefile
echo 'all: $(OBJS)' >>Makefile
echo '	@echo Tests Compiled' >>Makefile
